### ISSUE TITLE
Missing texture mappings for some block data values

### ISSUE THREAD

**Issue by sajones** [clarkx86/papyrusjs#9]
Missing texture mappings for data values for `still_lava`, `log`, `log2`, `composter_top`, `farmland`, `beetroot`, `carrots`, `potatoes`, `sapling`, `pumpkin_top`, `pumpkin_stem`, `chest_inventory_top`, `leaves`, and `planks`.

**Comment by clvrk** [comment]
Fixed with commit #https://github.com/clarkx86/papyrusjs/commit/47bc15920d3cbf371b6ba046dbc6187501fda9ee.
